package com.example.game.model;

import java.util.List;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@Entity
@Table(name="player")
public class Player {
	
	//email as pk and id as autogenerated value
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@NotBlank
    private String firstname;
	@NotBlank
    private String lastname;
	@NotBlank
	@Column(unique=true)
    private String email;
    private String description; 
	@Embedded
    private Address address;
	
	@ManyToOne(cascade=CascadeType.REMOVE )
	@JoinColumn(name="sponsor_id")
	private Sponsor sponsor;
	
	
	@ManyToMany( fetch = FetchType.LAZY, cascade= CascadeType.REMOVE)
	@JoinTable(
			name = "opponents",
			joinColumns = @JoinColumn(name ="player1_id", referencedColumnName = "id"),
			inverseJoinColumns= @JoinColumn(name = "player2_id", referencedColumnName = "id"))
	
	
	@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property ="id")
	@JsonIgnoreProperties({"opponents"})
	private List<Player> opponents;
    
    public Player(){
    	
    }
    
	
	public List<Player> getOpponents() {
		return opponents;
	}

   
	public void setOpponents(List<Player> opponents) {
		this.opponents = opponents;
	}


	public Player(String firstname, String lastname, String email, String description, Address address,Sponsor sponsor) {
		super();
		
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.description = description;
		this.address= address;
		this.sponsor=sponsor;
	}
	
	
	public Sponsor getSponsor() {
		return sponsor;
	}

	public void setSponsor(Sponsor sponsor) {
		this.sponsor = sponsor;
	}

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}

    
	 public Address getAddress() {
			return address;
		}

		public void setAddress(Address address) {
			this.address = address;
		}
	
	
	
	
}
